### ISSUE TITLE
Empty calendar in google calendar

### ISSUE THREAD

**Issue by JohanSF** [happylinks/TVCalendar#1]
Adding my link to Google Calendar yields a calendar, but none of my favorites show up, i.e. the calendar is empty.

Would you please be so kind as to test it again yourself (dev)? I suspect the script to be broken since it is 6 years old now.

Mine is: http://happylinks.nl/TVC/index.php?accountid=[D62AAA4979260D21]

Regards, Johan

**Comment by happylinks** [comment]
Hi Johan,

Nice to see you try my script! It's been 6 years indeed, so I wondered if it still worked. Just tested it and the php library I used, (bennu calendar) showed some PHP strict errors. But I turned off error reporting and now it seems to work again!

Your link is: http://happylinks.nl/TVC/index.php?accountid=D62AAA4979260D21 (without the [])

Hope you enjoy it.

Michiel

**Comment by JohanSF** [comment]
That was a quick reply! You should clarify that its without the brackets, maybe give an example or something like that.

Also, will it auto-update?

And lastly, as you see with my link that you posted just now, it seems to process the data but in google calendar the calendar is still empty.

Perhaps update Bennu? On sourceforge the newest version was released 2013-04-25.
Source: https://sourceforge.net/projects/bennu/

Johan

**Comment by happylinks** [comment]
Hi, just clarified the readme. Thanks for the tip :)

I use it in my iPhone calendar and that auto refreshes the link, I think it refreshes at least once a day, maybe more.

Can you let me know if the data isn't there after a day?

Just checked the ical, and the data in there seems to be correct. So it should work :)

**Comment by JohanSF** [comment]
Thank you for maintaining this :)
As I edited in above, maybe update Bennu, I don't know whats new, its your call.

I've needed something like this for a very very long time, auto refreshing sounds great.

Is it possible to download the ical file myself and then add that manually to google calendar to test, then I wouldn't have to wait a day haha :D

If not, I will let you now here tomorrow and if all is good we can close the issue.

**Comment by happylinks** [comment]
No problem!

Yeah I'll have a look at updating bennu. Don't know when though, maybe next weekend.

You can download the ical and save it as something.ical. I also tried validating it here http://icalendar.org/validator.html and it succeeded, so I'm pretty sure it should work :)
You can also force refresh in google calendar (https://www.binarysludge.com/2012/02/01/how-to-force-refresh-google-calendar/)

Let me know if you like it!

**Comment by JohanSF** [comment]
I tried the forcing method and it works, you are a genius, wow!

This just made my life incredibly more easy, thank you! - and please don't ever stop hosting the script!

Regards, Johan
